export const SAVE_RESPONSE = 'SAVE_RESPONSE'
export const RETRIEVE_RESPONSE = 'RETRIEVE_RESPONSE'
export const RETRIEVE_RESPONSES = 'RETRIEVE_RESPONSES'
export const UPDATE_RESPONSE = 'UPDATE_RESPONSE'

export const RETRIEVE_QUIZZES = 'RETRIEVE_QUIZZES'
