export const SAVE_RESPONSE = 'SAVE_RESPONSE'
export const RETRIEVE_RESPONSE_ITEM = 'RETRIEVE_RESPONSE_ITEM'
export const RETRIEVE_RESPONSE_LIST = 'RETRIEVE_RESPONSE_LIST'
export const UPDATE_CURRENT_RESPONSE = 'UPDATE_CURRENT_RESPONSE'

export const RETRIEVE_QUIZ_LIST = 'RETRIEVE_QUIZ_LIST'
